name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make unit-tests

      - name: Build Docker image
        run: docker build -t ${DOCKER_USERNAME}/fiap-health-med-auth:${{ github.sha }} -f Dockerfile .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: docker push ${DOCKER_USERNAME}/fiap-health-med-auth:${{ github.sha }}

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
